Fiserv/verifynow

config/product-layout.yaml

key value FTV133-commited and pushed

productoverview-keyvalue-FTV133

---

config/product-layout.yaml

Added Featured offerings

---

reference/1.0.0/sample.yaml

Revert "modified in sample.yaml"

---

reference/1.0.0/sample.yaml

Revert "added api page"

---

config/document-explorer-definition.yaml
docs/css-integration.md
docs/verifynow-functions.md
docs/verifynow-integration-guide.md
docs/verifynow-webserviceapi.md

Adding VN Documentation changes

Adding VN Documentation changes

---

docs/getting-started.md

Added get started md file - space added

added get started md file

---

config/product-layout.yaml

Bug fixing in product overview page

Bug fixing in productoverview page

---

reference/1.0.0/sample.yaml

Added changes for API Explorer, please review and Approve.

Added verifynow API Explorer

---

docs/getting-started.md

Added video in getting started

Added video in get started

---

config/document-explorer-definition.yaml
config/product-layout.yaml

Defect fixing reg RTVA name and product overview Page

Defect fixing reg RTVA name and product overview page

---

reference/1.0.0/sample.yaml

Modified API Explorer Content, please review and approve.

Feature 22

---

config/product-layout.yaml

Defect Fixing for product overview page

Defect Fixing for product overview page

---

config/product-layout.yaml

Buf fixing featured offerings

---

docs/getting-started.md

Reverted the testing code. Please provide approval.

Reverted the knowledge content and make Api as tab..

---

config/product-layout.yaml
docs/getting-started.md

Removed some content

---

docs/getting-started.md

reverting the changes

---

reference/1.0.0/sample.yaml

Added Request Parameters for Real Time Verification, Please Review and Approve.

Added Request Parameters for Real Time Verification

---

reference/1.0.0/sample.yaml

Added Response Parameter for Real Time Verification, please review and Approve.

Added Response Parameter for Real Time Verification

---

reference/1.0.0/sample.yaml

Revert "Added Response Parameter for Real Time Verification"

---

reference/1.0.0/sample.yaml

Modified Response Parameters of RTV

Modified Response Parameters of RTV

---

config/product-layout.yaml

committing product.yaml regarding bug in product overview page

committing product.yaml regarding bug in product overview page

---

reference/1.0.0/sample.yaml

Added Address in Request Parameter

Added Address in Request Parameter

---

docs/getting-started/before-you-start.md

before you start md file content and navigation fixed

before you start md file content and navigation fixed

---

reference/1.0.0/sample.yaml

Revert "Added Address in Request Parameter"

---

docs/getting-started/before-you-start.md
docs/getting-started/know-our-standard-api-structure.md

Before Start and Knowledge our API Changes

Before Start and Knowledge our API Changes

---

reference/1.0.0/sample.yaml

Added RTVA and Trail Deposit content

Added RTVA and Trail Deposit content

---

reference/1.0.0/sample.yaml

Modified Real time response

---

reference/1.0.0/sample.yaml

Removed Url from Real Time Verification

Ftv feature 22 10

---

reference/1.0.0/sample.yaml

Changed RTVA Response

---

reference/1.0.0/sample.yaml

Ftv feature 22 11

---

docs/getting-started/know-our-standard-api-structure.md
docs/getting-started/make-your-first-api-call.md

Make your First API call Changes!

Make your First API call Changes

---

docs/getting-started/before-you-start.md
docs/getting-started/know-our-standard-api-structure.md
docs/getting-started/make-your-first-api-call.md

Added Screenshots in Make your First API Call

Added Screenshots in Make your First API Call

---

reference/1.0.0/sample.yaml

Added Header in Instant Verification

Ftv feature 22 12

---

reference/1.0.0/sample.yaml

Modified header part

---

reference/1.0.0/sample.yaml

Modification done for VN API request and response

Modification done for VN API request and response

---

docs/getting-started.md
docs/getting-started/before-you-start.md
docs/getting-started/know-our-standard-api-structure.md

Bugs Fixed

---

reference/1.0.0/sample.yaml

Changing xml to json

---

reference/1.0.0/sample.yaml

 Added response codes

---

config/product-layout.yaml
reference/1.0.0/sample.yaml

Adding VN API response codes

---

docs/getting-started/know-our-standard-api-structure.md

added image correct path

---

docs/getting-started.md
docs/getting-started/before-you-start.md
docs/getting-started/know-our-standard-api-structure.md
docs/getting-started/make-your-first-api-call.md

proof reading for getting started

proof reading for getting started

---

docs/verifynow-account-verification-method/instant-verification.md

Modified for instant verfication page

Modified for instant verfication page

---

config/document-explorer-definition.yaml
docs/getting-started.md
reference/1.0.0/sample.yaml

VerifyNow changes

---

docs/widget-flow.md

Added Expandable feature for widget flow

Added Expandable feature for widget flow

---

docs/automated-account-additions.md

Added expandable feature for automated account addition

 Added expandable feature for automated account addition

---

docs/risk-controls.md

Redesign of risk-controls.md

---

docs/getting-started.md
docs/getting-started/know-our-standard-api-structure.md
docs/getting-started/make-your-first-api-call.md

Redesigning VN Getting Started

Redesigning VN Getting Started

---

docs/getting-started.md
docs/getting-started/know-our-standard-api-structure.md
docs/getting-started/make-your-first-api-call.md

Image src path added

---

docs/getting-started.md
docs/getting-started/know-our-standard-api-structure.md
docs/getting-started/make-your-first-api-call.md

Changed Image Path and commented lines

Changed Image Path and commented lines

---

docs/getting-started.md
docs/getting-started/know-our-standard-api-structure.md
docs/getting-started/make-your-first-api-call.md

Response and Request BG Changed

Response and Request BG Changed

---

docs/automated-account-additions.md
docs/widget-flow.md

Added images in automated account addition

Added images in automated account addition

---

docs/automated-account-additions.md
docs/widget-flow.md

modified widget-flow md file

---

docs/getting-started/make-your-first-api-call.md

Removed <br>

---

docs/getting-started.md
docs/getting-started/know-our-standard-api-structure.md
docs/getting-started/make-your-first-api-call.md

Removed Image width

---

docs/getting-started.md
docs/getting-started/before-you-start.md
docs/getting-started/know-our-standard-api-structure.md

Changed Verify now text

---

docs/widget-flow.md

Widget placement test

---

docs/getting-started.md
docs/getting-started/know-our-standard-api-structure.md
docs/getting-started/make-your-first-api-call.md

Changed BG Color

---

docs/automated-account-additions.md
docs/widget-flow.md

fixed for bug 1002 and 1004 (API flow link)

fixed for bug 1002 and 1004

---

docs/automated-account-additions.md

 corrected spelling for oauth

---

docs/automated-account-additions.md
docs/widget-flow.md

 reduced the bullet point size

---

docs/widget-flow.md

Added content for Widget flow

---

docs/getting-started/know-our-standard-api-structure.md

Changed BG white color in "Know our API Standard Structure"

Changed BG white color

---

docs/getting-started.md
docs/getting-started/make-your-first-api-call.md

Changed BG White Color in getting started

Changed BG White Color in getting started

---

docs/widget-flow.md

VN Bug fix for md file redirection

VN Bug fix for md file redirection

---

config/document-explorer-definition.yaml
docs/verifynow-account-verification-method.md

modified documentation file and images path

 modified documentation file and images path

---

docs/account-verification-methods.md
docs/automated-account-additions.md
docs/getting-started.md
docs/getting-started/before-you-start.md

Note Design changed

---

docs/widget-flow.md

Redesign changes for VN in widgetflow.md

Redesign changes for VN in widgetflow.md

---

docs/verifynow-account-verification-method.md

VN Redesign Bugfix

---

docs/automated-account-additions.md
docs/getting-started.md
docs/getting-started/before-you-start.md
docs/getting-started/make-your-first-api-call.md
docs/verifynow-account-verification-method.md
docs/verifynow-account-verification-method/instant-verification.md
docs/verifynow-account-verification-method/trial-deposit-verification.md

Note and Content in separate lines.

Note and Content in separate lines

---

docs/verifynow-account-verification-method.md
docs/verifynow-account-verification-method/instant-verification.md
docs/verifynow-account-verification-method/real-time-verification.md

 bug fix for vn redesign

---

docs/widget-flow.md

Bug fix for VN redesign in widgetflow page

Bug fix for VN redesign in widgetflow page

---

docs/getting-started/know-our-standard-api-structure.md
docs/getting-started/make-your-first-api-call.md

Added collasible sign in Know our API Std and Make API Call

Added collasible sign in Know our API Std and Make API Call

---

config/document-explorer-definition.yaml
docs/release-notes/march.md
reference/1.0.0/sample.yaml

Added Release Notes

---

config/product-layout.yaml
docs/automated-account-additions.md
docs/risk-controls.md
docs/verifynow-account-verification-method.md
reference/1.0.0/sample.yaml

VN committing changes regarding enhancements

VN committing changes regarding enhancements

---

docs/risk-controls.md

added statement in risk control

added statment in risk control

---

docs/risk-controls.md

changed statement in risk control

changed statement in risk control

---

reference/1.0.0/sample.yaml

Adding VN Instant verification API

Adding VN Instant verification API

---

reference/1.0.0/sample.yaml

Changing operationID for API language issue fix

Changing operationID for API language issue fix

---

docs/add-account-manually.md

Add Account manually changes for VN enhancement

Add Account manually changes for VN enhancement

---

docs/verifynow-account-verification-method/instant-verification.md

Instant verification file VN rework

Instant verification file VN rework

---

reference/1.0.0/sample.yaml

Adding request and response parameters to verify now API

Feature1234

---

reference/1.0.0/openapi.yaml

Adding VN request and response

Adding VN request and response

---

reference/1.0.0/openapi.yaml

Adding VN request and response

Adding request and response params

---

reference/1.0.0/openapi.yaml

Adding headers in VN API
